### ISSUE TITLE
Inquiry about skull stripping of CTA images

### ISSUE THREAD

**Issue by zhaofenqiang** [gzq17/Weakly-Supervised-by-MIP#2]
Hi,

Thanks for the great work and the released code! I am very interested in your work and have tried to reimplement the work and the results. During the reimplementation, I encountered an issue and hope you could clarify it for me.

As stated in the paper, "for CTA data, the skull region is highlighted, affecting the segmentation of blood vessels and causing obstruction during MIP. To mitigate this issue, the CTA data has been performed skull-stripping to remove the bright skull regions [38]." However, when I tried to use the skull-stripping code of [38], specifically this script [https://github.com/muschellij2/CT_BET/blob/master/Skull_Strip_Paper/CT_Skull_Strip_Example.sh](https://github.com/muschellij2/CT_BET/blob/master/Skull_Strip_Paper/CT_Skull_Strip_Example.sh), the extracted brain does not include the vertebral arteries. In other words, the skull stripping code is so useful and effective that it can only retain the whole connected brain, which does achieve the goal of skull stripping but does not achieve the goal of further vessel segmentation. As shown in the image below, the important vertebral arteries are removed as part of the skull during skull stripping. So I am wondering if I am performing the skull-stripping correctly, or if the vertebral arteries were supposed to be removed? If the former, could you share your skull-stripping scripts with me? If the latter, this will bring up another critical issue, as follows.
<img width="561" alt="f0e99c5989ab4ed619065743ca8a9625" src="https://github.com/user-attachments/assets/ac64dadd-4317-4008-9083-f54165b48e48">

The vessels in the brain CTA images should be similar to the one shown below. It is clear that the vertebral arteries and carotid arteries are both present and should be segmented
<img width="561" alt="12bce11e1b22d54174d556dca67b095a" src="https://github.com/user-attachments/assets/a2a366fd-e6ad-4d90-bfec-d0e5c73ec218">
But the vessels shown in your paper all look like this, which misses the vertebral arteries and most carotid arteries.
<img width="281" alt="1722574616727_DDBBA045-8BB4-439c-AF95-5E7F88A65E00" src="https://github.com/user-attachments/assets/8d2414b7-d782-4929-9912-6440c54faa1a">

I am not familiar with the MRA images, so I cannot comment on the vascular segmentation results of MRA in your paper. But for brain CTA images, in my opinion, if skull stripping is performed before vessel segmentation, the vertebral and carotid arteries located within the bones will be inevitably removed along with the skull, regardless of the skull-stripping methods you used. So do you have any ideas or plans to improve this aspect of the method?

Thank you very much for your time and consideration. I am looking forward to your response!

**Comment by gzq17** [comment]
Thank you very much for your attention to our work. As you can see, the blood vessels we segmented are mainly Willis circles and their small extensions. The vertebral artery and carotid artery are not included (or only a small part). This is mainly for comparison with the public dataset TubeTK [1], so we did not involve the relevant issues you mentioned in the process of removing the skull. I am very sorry for not providing you with relevant help.
[1]https://public.kitware.com/Wiki/TubeTK/Data
